#!/usr/bin/env bash
# setup_neteco_proxy.sh — Phase 1: expose bht-api at port 31943 for NetEco push callbacks.
#
# NetEco NBI listens on HTTPS :31943. When NetEco is configured to push alarm
# notifications to our system, it targets https://<our-ip>:31943/ingest/neteco/push.
# bht-api runs plain HTTP on :8080, so we need a TLS-terminating reverse proxy.
#
# Run as root on Rocky 9 (192.168.108.88):
#   bash setup_neteco_proxy.sh
#
# Prerequisites: nginx, openssl  (dnf install -y nginx openssl)
# If nginx is unavailable, the script falls back to a firewalld REDIRECT rule (HTTP only).

set -euo pipefail

BHT_API_PORT=8080
PROXY_PORT=443        # Standard HTTPS. Port 31943 is the NetEco SERVER's own web port — do not re-use it here.
CERT_DIR="/opt/bht/config/tls"
NGINX_CONF="/etc/nginx/conf.d/bht-neteco-proxy.conf"

# ------------------------------------------------------------------ TLS cert
mkdir -p "$CERT_DIR"
if [[ ! -f "$CERT_DIR/server.crt" ]]; then
  echo "[proxy] generating self-signed TLS cert (replace with CA-signed cert in production)"
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -keyout "$CERT_DIR/server.key" \
    -out    "$CERT_DIR/server.crt" \
    -subj "/CN=bht-api/O=BHT/C=BA" \
    -addext "subjectAltName=IP:192.168.108.88"
  chmod 640 "$CERT_DIR/server.key"
  chown root:bht "$CERT_DIR/server.key" "$CERT_DIR/server.crt"
  echo "[proxy] cert written to $CERT_DIR"
else
  echo "[proxy] using existing cert at $CERT_DIR"
fi

# ------------------------------------------------------------------ nginx
if command -v nginx &>/dev/null; then
  cat > "$NGINX_CONF" <<NGINX
# NetEco NBI push callback proxy — TLS :${PROXY_PORT} → HTTP :${BHT_API_PORT}
# Generated by setup_neteco_proxy.sh — edit manually if needed.
server {
    listen ${PROXY_PORT} ssl;
    server_name _;

    ssl_certificate     ${CERT_DIR}/server.crt;
    ssl_certificate_key ${CERT_DIR}/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # NetEco OAuth2 token endpoint (called by NetEco before each push session)
    location /api/neteco/token {
        proxy_pass         http://127.0.0.1:${BHT_API_PORT};
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_read_timeout 10s;
    }

    # Alarm push callback
    location /ingest/neteco/push {
        proxy_pass         http://127.0.0.1:${BHT_API_PORT};
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_read_timeout 30s;
    }

    # Health-check redirect for NetEco connectivity test
    location /api/health {
        proxy_pass         http://127.0.0.1:${BHT_API_PORT};
        proxy_read_timeout 10s;
    }

    location / { return 404; }
}
NGINX
  nginx -t && systemctl enable --now nginx && systemctl reload nginx
  echo "[proxy] nginx configured: HTTPS :${PROXY_PORT} → HTTP :${BHT_API_PORT}"

else
  echo "[proxy] nginx not found — falling back to firewalld REDIRECT (HTTP only, no TLS)"
  echo "[proxy] WARNING: NetEco push requires HTTPS. Install nginx for production use."
  firewall-cmd --permanent \
    --add-forward-port="port=${PROXY_PORT}:proto=tcp:toport=${BHT_API_PORT}:toaddr=127.0.0.1"
  firewall-cmd --permanent --add-port="${PROXY_PORT}/tcp"
  firewall-cmd --reload
  echo "[proxy] firewalld rule: :${PROXY_PORT} → :${BHT_API_PORT}"
fi

# ------------------------------------------------------------------ verify
echo ""
echo "=== Verify ==="
echo "curl -sk https://127.0.0.1:${PROXY_PORT}/api/health && echo 'proxy OK'"
echo ""
echo "NetEco OpenAPI Management — Third-Party System Configuration:"
echo "  Domain Name:   192.168.108.88"
echo "  Port:          443"
echo "  Login Address: /api/neteco/token"
echo "  Push URL:      https://192.168.108.88/ingest/neteco/push"
echo "  (configure client_secret in /opt/bht/config/api.toml [neteco_auth])"
echo ""
echo "=== Vi swap cleanup (if .neteco.env was open during a crash) ==="
echo "  rm -f /opt/bht/config/.neteco.env.swp /opt/bht/config/.neteco.env.swo"
